name: Deploy to algolia

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to algolia
    runs-on: ubuntu-latest
    steps:
      - name: test env
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: env

      - name: Run DocSearch Scraper
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          docker run \
          -e APPLICATION_ID -e API_KEY \
          -e CONFIG="$(cat .github/scrapeConfig/docusaurus-v2.json)" \
          algolia/docsearch-scraper
