name: Deploy to algolia

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to algolia
    runs-on: ubuntu-latest
    steps:
      - name: Run DocSearch Scraper
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: ${{ secrets.DCONFIG }}
        run: |
          docker run \
          -e APPLICATION_ID -e API_KEY \
          -e CONFIG \
          algolia/docsearch-scraper
